// Install test-only engine: npm install --prefix .security-tools --no-save --package-lock=false @electric-sql/pglite
import { PGlite } from '../.security-tools/node_modules/@electric-sql/pglite/dist/index.js';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const admin = '11111111-1111-4111-8111-111111111111';
const outsider = '22222222-2222-4222-8222-222222222222';
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated;
 CREATE SCHEMA auth; CREATE SCHEMA storage;
 CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz);
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 GRANT USAGE ON SCHEMA auth,storage,public TO anon,authenticated;
 CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 CREATE TABLE storage.objects(id text PRIMARY KEY,bucket_id text);
 ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
 GRANT SELECT,INSERT,UPDATE,DELETE ON storage.objects TO anon,authenticated;
 CREATE POLICY "existing broad storage policy" ON storage.objects FOR ALL TO authenticated USING(true) WITH CHECK(true);
 INSERT INTO auth.users VALUES ('${admin}','lalusispartners@gmail.com',now()),('${outsider}','outsider@example.test',now());
 CREATE TABLE public.unrelated_project(id text);
 INSERT INTO public.unrelated_project VALUES ('untouched');
 GRANT SELECT ON public.unrelated_project TO authenticated;
`);
const schema = readFileSync(new URL('../supabase/migrations/20260926_initial_cms_schema.sql',import.meta.url),'utf8');
await db.exec(schema.replace('CREATE EXTENSION IF NOT EXISTS "pgcrypto";',''));
const migration = readFileSync(new URL('../supabase/migrations/20260929_admin_authorization.sql',import.meta.url),'utf8');
await db.exec(migration); // Re-runs must be safe.
const videoMigration = readFileSync(new URL('../supabase/migrations/20260930_video_media.sql',import.meta.url),'utf8');
await db.exec(videoMigration);
await db.exec(videoMigration);
const allowedTypes = (await db.query("SELECT allowed_mime_types FROM storage.buckets WHERE id='media'")).rows[0].allowed_mime_types;
assert.ok(allowedTypes.includes('video/mp4') && allowedTypes.includes('video/webm') && allowedTypes.includes('image/jpeg'));
await db.exec(readFileSync(new URL('../supabase/migrations/20260930_video_100mb.sql',import.meta.url),'utf8'));
assert.equal(Number((await db.query("SELECT file_size_limit FROM storage.buckets WHERE id='media'")).rows[0].file_size_limit),104857600);
await db.exec(`INSERT INTO public.pages(id,slug,title,is_published) VALUES ('public','public','Public',true),('draft','draft','Draft',false);
 INSERT INTO public.contact_messages(id,full_name,email,message) VALUES ('private','Client','client@example.test','Private concern');
 INSERT INTO storage.objects VALUES ('portrait','media');`);
async function as(role,id='') { await db.exec(`RESET ROLE; SET request.jwt.claim.sub = '${id}'; SET ROLE ${role};`); }
async function count(sql,n) { assert.equal((await db.query(sql)).rows.length,n,sql); }
await as('anon');
await count('SELECT * FROM public.pages',1);
await assert.rejects(db.query('SELECT * FROM public.contact_messages'));
await assert.rejects(db.exec("INSERT INTO public.pages(id,slug,title) VALUES ('bad','bad','bad')"));
await db.exec("INSERT INTO public.contact_messages(id,full_name,email,message) VALUES ('submission','Client','client@example.test','New concern')");
await db.exec("INSERT INTO public.consultation_requests(id,reference_number,full_name,email_address,contact_number,brief_concern,status) VALUES ('consult','ref','Client','client@example.test','','Concern','new')");
await assert.rejects(db.exec("INSERT INTO public.contact_messages(id,full_name,email,message,status) VALUES ('fake','Client','client@example.test','Concern','read')"));
await as('authenticated',outsider);
assert.equal((await db.query('SELECT public.is_lawfirm_admin() AS approved')).rows[0].approved,false);
await count('SELECT * FROM public.contact_messages',0);
await count('SELECT * FROM public.pages',1);
await count('SELECT * FROM public.unrelated_project',1);
await assert.rejects(db.exec("INSERT INTO public.pages(id,slug,title) VALUES ('bad','bad','bad')"));
await assert.rejects(db.exec("INSERT INTO lawfirm_private.admin_users(user_id) VALUES ('"+outsider+"')"));
await assert.rejects(db.exec("INSERT INTO storage.objects VALUES ('bad','media')"));
await count("DELETE FROM storage.objects WHERE id='portrait' RETURNING id",0);
await count("UPDATE storage.objects SET bucket_id='other' WHERE id='portrait' RETURNING id",0);
await db.exec("INSERT INTO storage.objects VALUES ('other-project','other')");
await assert.rejects(db.exec("UPDATE storage.objects SET bucket_id='media' WHERE id='other-project'"));
await as('authenticated',admin);
assert.equal((await db.query('SELECT public.is_lawfirm_admin() AS approved')).rows[0].approved,true);
await count('SELECT * FROM public.contact_messages',2);
await count('SELECT * FROM public.pages',2);
await db.exec("INSERT INTO public.pages(id,slug,title) VALUES ('admin','admin','Admin'); INSERT INTO storage.objects VALUES ('admin-photo','media')");
await count("DELETE FROM storage.objects WHERE id='admin-photo' RETURNING id",1);
await db.exec('RESET ROLE');
await db.exec(`DELETE FROM lawfirm_private.admin_users WHERE user_id='${admin}'`);
await as('authenticated',admin);
assert.equal((await db.query('SELECT public.is_lawfirm_admin() AS approved')).rows[0].approved,false);
await count('SELECT * FROM public.contact_messages',0);
await db.close();
console.log('PASS: public intake, private records, drafts, admin approval/revocation, storage bypass protection, unrelated tables, repeat migration');
