import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
import vm from 'node:vm';
let encoded = new Blob(['small'], { type: 'image/webp' });
let revoked = 0;
let decodes = 0;
const canvas = { width: 0, height: 0, getContext: () => ({drawImage() {}}), toBlob: cb => cb(encoded) };
const context = vm.createContext({ File, Blob, URL: {createObjectURL: () => 'blob:test', revokeObjectURL: () => revoked++}, Image: class { naturalWidth=4000; naturalHeight=6000; async decode(){ decodes++; } }, document: {createElement: () => canvas} });
const source = readFileSync(new URL('../src/lib/imagePerformance.ts', import.meta.url), 'utf8');
vm.runInContext(stripTypeScriptTypes(source.replaceAll('export ', '')), context);
const jpeg = new File([new Uint8Array(300000)], 'portrait.jpg', {type:'image/jpeg'});
const optimized = await context.optimizePhotoUpload(jpeg);
assert.equal(optimized.type, 'image/webp');
assert.equal(optimized.name, 'portrait.webp');
assert.equal(canvas.height, 1600);
assert.equal(canvas.width, 1067);
assert.equal(revoked, 1);
encoded = new Blob([new Uint8Array(400000)], {type:'image/webp'});
assert.equal(await context.optimizePhotoUpload(jpeg), jpeg, 'never upload a larger conversion');
const gif = new File([new Uint8Array(300000)], 'animated.gif', {type:'image/gif'});
assert.equal(await context.optimizePhotoUpload(gif), gif, 'preserve animated formats');
const small = new File(['small'], 'small.jpg', {type:'image/jpeg'});
assert.equal(await context.optimizePhotoUpload(small), small);
assert.equal(decodes, 2);
console.log('PASS: photo resizing, smaller files only, original formats preserved, URLs released');
