import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp, mkdir, writeFile, readFile, readdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createDatabase, migrateBackend } from '../server/database';
import { seedContent } from '../server/seed-content';
import { publicSnapshot } from '../server/public-content';
import { migrateMedia } from '../server/media-migration';
import { createApp } from '../server/app';
import { hashPassword } from '../server/auth';
import { sha256, mediaRoot } from '../server/media';

test('media migration, uploads, persistent files and MySQL public build',async()=>{
  assert.equal(process.env.DB_NAME,'lalusis_migration_test');
  const db=createDatabase();const [existing]:any=await db.query('SHOW TABLES');assert.equal(existing.length,0);
  const temp=await mkdtemp(path.join(tmpdir(),'lalusis-migration-'));
  let server:ReturnType<ReturnType<typeof createApp>['listen']>|undefined;
  const close=async()=>{if(server){await new Promise<void>(resolve=>server!.close(()=>resolve()));server=undefined;}};
  try{
    const schema=await readFile('tests/fixtures/mysql-schema.sql','utf8');
    for(const sql of schema.match(/CREATE TABLE[^;]+;/g)!)await db.query(sql);
    await migrateBackend(db);
    await db.execute('INSERT INTO app_admins (id,email,password_hash) VALUES (?,?,?)',[randomUUID(),'admin@example.test',hashPassword('test-only-long-password')]);
    const before=await seedContent(db);assert.equal(before.practice_areas,14);
    const [empty]:any=await db.query('SELECT COUNT(*) n FROM pages');assert.equal(empty[0].n,0);
    await seedContent(db,true);assert.ok(Object.values(await seedContent(db,true)).every(n=>n===0));
    await db.execute("UPDATE pages SET title='Preserve imported title' WHERE slug='about'");await seedContent(db,true);
    const [preserved]:any=await db.query("SELECT title FROM pages WHERE slug='about'");assert.equal(preserved[0].title,'Preserve imported title');
    await db.execute("INSERT INTO pages (id,slug,title,is_published,sections) VALUES ('draft','secret-draft','PRIVATE_DRAFT_MARKER',0,'[]')");
    await db.execute("INSERT INTO attorneys (id,slug,full_name,professional_title,is_published) VALUES ('attorney','test-attorney','Test Attorney','Partner',1),('draft-attorney','private-attorney','PRIVATE_ATTORNEY_MARKER','Partner',0)");
    const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aewoAAAAASUVORK5CYII=','base64');
    const backup=path.join(temp,'backup'),destination=path.join(temp,'persistent');
    await mkdir(path.join(backup,'storage/media/uploads'),{recursive:true});
    const source=path.join(backup,'storage/media/uploads/test.png');await writeFile(source,png);
    const hash=await sha256(source),manifest=[{Path:'/media/uploads/test.png',Bytes:png.length,SHA256:hash}];
    await writeFile(path.join(backup,'storage-manifest.json'),'\uFEFF'+JSON.stringify(manifest));
    const legacyOrigin='https://test-project.supabase.co',old=legacyOrigin+'/storage/v1/object/public/media/uploads/test.png';
    await db.execute('INSERT INTO media (id,name,storage_path,url,file_type) VALUES (?,?,?,?,?)',['existing-media','Test','uploads/test.png',old,'image']);
    await db.execute('UPDATE pages SET sections=? WHERE id=?',[JSON.stringify([{id:'test-image',type:'image',content:{url:old}}]),'draft']);
    const preview=await migrateMedia(db,{backup,destination,legacyOrigin});assert.equal(preview.verifiedFiles,1);assert.equal(preview.applied,false);
    const [unchanged]:any=await db.query("SELECT url FROM media WHERE id='existing-media'");assert.equal(unchanged[0].url,old);
    await writeFile(source,'corrupt');await assert.rejects(migrateMedia(db,{backup,destination,legacyOrigin,apply:true}),/hash or size mismatch/);await writeFile(source,png);
    const applied=await migrateMedia(db,{backup,destination,legacyOrigin,apply:true});assert.equal(applied.changedRows,2);
    const repeated=await migrateMedia(db,{backup,destination,legacyOrigin,apply:true});assert.equal(repeated.changedRows,0);assert.equal(repeated.insertedMedia,0);
    const [updated]:any=await db.query("SELECT sections FROM pages WHERE id='draft'");assert.equal(updated[0].sections[0].content.url,'/media/existing-media');
    await assert.rejects(mediaRoot(path.join(process.cwd(),'dist','uploads')),/deployment-managed/);
    const snapshot=await publicSnapshot(db);assert.ok(!JSON.stringify(snapshot).includes('PRIVATE_'));assert.equal(snapshot.practice_areas.length,14);assert.equal(snapshot.media,undefined);
    const origin='http://localhost:31999';
    const start=async()=>{server=createApp(db,{origin,mediaRoot:destination,secureCookies:false}).listen(0,'127.0.0.1');await new Promise<void>(r=>server!.once('listening',r));return 'http://127.0.0.1:'+(server!.address() as any).port;};
    let base=await start();
    const login=await fetch(base+'/api/auth/login',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({email:'admin@example.test',password:'test-only-long-password'})});assert.equal(login.status,200);
    const cookie=login.headers.get('set-cookie')!.split(';')[0];
    const upload=(body:Buffer,authenticated=true)=>fetch(base+'/api/admin/media/upload?filename=test.png&name=Test&category=general',{method:'POST',headers:{Origin:origin,'Content-Type':'application/octet-stream',...(authenticated?{Cookie:cookie}:{})},body});
    assert.equal((await upload(png,false)).status,401);
    assert.equal((await upload(Buffer.from('<svg onload="alert(1)"></svg>'))).status,415);
    const response=await upload(png);assert.equal(response.status,201);const media=await response.json();
    assert.equal((await fetch(base+media.url)).headers.get('content-type'),'image/png');
    assert.deepEqual(Buffer.from(await (await fetch(base+media.url)).arrayBuffer()),png);
    const ranged=await fetch(base+media.url,{headers:{Range:'bytes=0-7'}});assert.equal(ranged.status,206);assert.equal((await ranged.arrayBuffer()).byteLength,8);
    await close();base=await start();assert.equal((await fetch(base+media.url)).status,200,'Media persists across server restarts');
    assert.equal((await fetch(base+'/media/existing-media')).status,200);
    const mutation=async(action:string,body:any)=>fetch(base+'/api/admin/media/'+media.mediaItem.id+'/'+action,{method:'POST',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify(body)});
    assert.equal((await mutation('update',{name:'Edited',altText:'Edited image',category:'branding',url:'https://evil.test'})).status,200);
    const [metadata]:any=await db.execute('SELECT name,url FROM media WHERE id=?',[media.mediaItem.id]);assert.equal(metadata[0].name,'Edited');assert.equal(metadata[0].url,media.url);
    await db.execute('UPDATE media SET storage_path=? WHERE id=?',['../private',media.mediaItem.id]);assert.equal((await fetch(base+media.url)).status,400);
    await db.execute('UPDATE media SET storage_path=? WHERE id=?',[media.storagePath,media.mediaItem.id]);
    assert.equal((await mutation('delete',{})).status,200);assert.equal((await fetch(base+media.url)).status,404);
    assert.ok(!(await readdir(destination)).includes(media.storagePath));
    assert.equal((await fetch(base+'/api/content/media')).status,404);
    await close();
    // Exercise the real build: credentials stay server-side, drafts stay out of generated HTML.
    await new Promise<void>((resolve,reject)=>{
      const child=spawn(process.env.ComSpec||'cmd.exe',['/d','/s','/c','npm.cmd run build:hostinger'],{env:{...process.env,VITE_BACKEND:'mysql',VITE_SITE_URL:'https://lalusispartnerslaw.com'},stdio:['ignore','pipe','pipe']});
      let output='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);child.on('error',reject);child.on('close',code=>code===0?resolve():reject(new Error('MySQL build failed:\n'+output)));
    });
    const sitemap=await readFile('dist/sitemap.xml','utf8');assert.ok(sitemap.includes('/attorneys/test-attorney'));assert.ok(!sitemap.includes('private-attorney'));assert.ok(!sitemap.includes('secret-draft'));
    const html=await readFile('dist/index.html','utf8');assert.ok(html.includes('Legal Precision'));assert.ok(!html.includes('PRIVATE_'));assert.ok(!html.includes('app_admins'));assert.ok(!html.includes(process.env.DB_PASSWORD!));
  }finally{await close();await db.end();await rm(temp,{recursive:true,force:true});}
});
